# Generated by Django 4.1.2 on 2022-10-15 01:44

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(error_messages={'blank': 'blank', 'invalid': 'invalid', 'unique': 'taken'}, max_length=255, unique=True)),
                ('phone_number', models.CharField(error_messages={'blank': 'blank', 'max_length': {'count': '%(show_value)d', 'error': 'too long'}, 'min_length': {'count': '%(show_value)d', 'error': 'too shoort'}, 'unique': 'taken'}, max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format E.164'.", regex='^\\+[1-9]\\d{1,14}$'), django.core.validators.MinLengthValidator(11)])),
                ('birthdate', models.DateField(error_messages={'blank': 'blank'}, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today, message='in the future')])),
                ('first_name', models.CharField(error_messages={'blank': 'blank'}, max_length=200)),
                ('last_name', models.CharField(error_messages={'blank': 'blank'}, max_length=200)),
                ('country_code', models.CharField(error_messages={'blank': 'blank'}, max_length=200)),
                ('gender', models.CharField(error_messages={'blank': 'blank'}, max_length=200)),
                ('avatar', models.ImageField(error_messages={'blank': 'blank'}, max_length=200, upload_to='')),
                ('status', models.BooleanField(default=True, error_messages={'blank': 'blank'})),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
