# Generated by Django 4.1.2 on 2022-10-15 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_myuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='status',
        ),
    ]
